### ISSUE TITLE
plugin needed to use other plugins

### ISSUE THREAD

**Issue by Sicoval31** [ericferon/glpi-statecheck#19]
Hi, 
the plugin statecheck is needed to use  the arhisw plugin.
This last one is also needed to use the dataflows inventory ....

Please make all this plugin not depend on this other plugins.

Thx
-----

le plugin statechecke st indispensable (et demandé) pour pouvoir utiliser le plugin structure d'applications, lui même indispensable pour utiliser le plugin flux de données.
C'est lourd ...
Merci de désolidariser ces plugins qui devraient être independants, d'autant plus que des éléments sont deja présent dans le coeur de GLPI

**Comment by ericferon** [comment]
Hi,
I can understand that these dependencies are annoying at installation time.
But the dataflows dependency to archisw exists for a long time.
The archisw dependency to statecheck is new, and needed to avoid errors when configuring the fields.
So, I don't want to remove them, otherwise this means more support for me to identify errors and propose solutions. This can be avoided with 2 minutes of your time, from time to time.
K.r,

**Comment by Sicoval31** [comment]
Je comprends, mais comme il n'y a pas de liens avec le coeur de GLPI et que finalement les plugins ne correspondent aps à nos besoins (et raduction partielle qui plus est) : desinstallation de ceux-ci
