### ISSUE TITLE
Error on GLPI 10.0.17

### ISSUE THREAD

**Issue by ppenin** [ericferon/glpi-statecheck#30]
Hi,

After GLPI update to GLPI 10.0.17, Statecheck cannot be activated.

Error: PHP Compile Error (64): Declaration of PluginStatecheckRule::checkCriteria(&$criteria, &$input) must be compatible with Rule::checkCriteria($criteria, &$input) in /var/www/html/glpi/marketplace/statecheck/inc/rule.class.php at line 1348

Regards.

**Comment by raregtp** [comment]
Just ran into this one also, can confirm the same set of circumstances.

**Comment by raregtp** [comment]
Looking at this closer, I *think* the issue is the leading '&' before '$criteria' in line 1348 of var/www/html/glpi/marketplace/statecheck/inc/rule.class.php.  Line 1348 looks like this...

     function checkCriteria(&$criteria, &$input) {

...to which I adjusted mine to look like...

     function checkCriteria($criteria, &$input) {

After making this adjustment I can now activate the plugin.  That said, while I dabble in PHP and know enough to be dangerous, I have no solid idea if this is the only thing that needs to be done or if other adjustments need to be made to the code.  I suspect this was a typo, but hopfully the author can chime in and let us know if this is indeed the "fix".

Thanks!!

**Comment by ppenin** [comment]
Thanks for the tip. I was able to activate the plugin statecheck

**Comment by ericferon** [comment]
Hi,
This is not a typo.
The function checkCriteria has changed, in the core class Rule.
It has been updated in v2.4.4.
K.r,

**Comment by raregtp** [comment]
Thanks for the feedback and the quick fix!!  I suspected it likely wasn't that simple.  Will test ASAP.

**Comment by ppenin** [comment]
Hi,
i tested 2.4.4 version on GLPI 10.0.17 and it works well.
Thank you for the fix
